//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_finall.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Inboxes = new HashSet<Inbox>();
        }
    
        public int Id_Customer { get; set; }
        public string Name_Customer { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string P_Number { get; set; }
        public string Email { get; set; }
        public string Home { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inbox> Inboxes { get; set; }
    }
}
