//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_finall.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        public int Id_Inbox { get; set; }
        public string Number_Inbox { get; set; }
        public Nullable<System.DateTime> Date_Inbox { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string Note { get; set; }
        public int Id_Customer { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
