//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_finall.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_Products { get; set; }
        public string Name_Products { get; set; }
        public string Img { get; set; }
        public string Summary_Content { get; set; }
        public Nullable<System.DateTime> Date_Submitted { get; set; }
        public int Id_Type_Product { get; set; }
        public string Name_Type_Product { get; set; }
        public string Content { get; set; }
        public string Username { get; set; }
        public Nullable<bool> DADUYET { get; set; }
        public Nullable<int> Gia { get; set; }
        public string Content_Gia { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Type_Product Type_Product { get; set; }
    }
}
